name: chatbot

volumes:
  ollama:
    driver_opts:
      type: none
      device: /mnt/data/ollama
      o: bind
  open-webui:
    driver_opts:
      type: none
      device: /mnt/data/open-webui
      o: bind

services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "8080:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_AUTH=false
      - DEFAULT_MODELS=llama3.3:latest
    depends_on:
      ollama:
        condition: service_started
